const express =require('express')
const app=express()
const dotenv=require('dotenv')
const cors =require('cors')
const Authentication=require("./routes/Users")
const Recipes=require("./routes/Recipes")
dotenv.config()
app.use(express.json())
app.use(cors({ origin:"http://localhost:3000"}))
app.use("/uet",Authentication)
app.use("/uet",Recipes)
app.listen(process.env.PORT,()=>{
    console.log("server is running",process.env.PORT)
})